### ISSUE TITLE
Not always works as expected

### ISSUE THREAD

**Issue by intraector** [caseyryan/flutter_focus_catcher#1]
Sometimes keyboard hides the TextField. Not sure why, just 1 of 5-10 times it doesn't lift up the screen. Huawei 8x, Android 9.

It would be great to have exactly the same plugin but without custom lifting of the screen, leaving this to standard Scaffold's `resizeToAvoidBottomInset: false`. 

And working properly as well :)
![Screenshot_20191229_105811_com example six_sek](https://user-images.githubusercontent.com/51683067/71554035-f83d9580-2a2a-11ea-8bd1-9cbe9dfd449a.jpg)

![Screenshot_20191229_105821_com example six_sek](https://user-images.githubusercontent.com/51683067/71554034-f83d9580-2a2a-11ea-8cdf-0b370abd2887.jpg)

**Comment by caseyryan** [comment]
Возможно дело в анимации, которая используется для подъема. Можно какой-нибудь минимальный пример, в котором этот баг воспроизводится? Попробую пофиксить
